### ISSUE TITLE
Steam Deck Guide May Not Work

### ISSUE THREAD

**Issue by EtoZamamai** [silent-destroyer/tunic-randomizer#13]
Love the mod, but the Steam Deck guide did not work for me for my steam version of Tunic.  The issue is that proton tricks picks the wrong folder to apply the dll overide to and doesn't seem to have a way to change it.  In order to get bepinex to work for Tunic specifically you seem to need to use another version of wine tricks.

For me I set up Tunic in a wine prefix in the Lutris app.

1. Download Lutris app, configure your steam library.
2. Download tunic through lutris (probably not necessary)
3.  Hit configure and change the runner to wine
5.  Under game options select the executable as tunic.exe (you can find it by right-clicking tunic in steam-manage-browse local files)
6. Under wine prefix select a location for the game files to be stored (I chose /home/deck/Games/Tunic but you can choose any location)
7.  Extract the bepinex x64 file found in the tunic randomizer to your tunic folder (can be done in any step, the tunic folder should be located in /home/deck/Games/Tunic/dosdevices/d:/steamapps/common/TUNIC/ during this step)
8. In Lutris click on the wine glass next to play and open up wine tricks-select the default wineprefix-install a windows DLL or component-select winhttp and hit ok.
9. Launch Tunic through Lutris to activate bepinex
10.  The bepinex folder you extracted in step 7 should now have new folders including plugins-put the "TunicRandomizer.dll" you downloaded in the newly created plugin folder
11.  Next time you launch through Lutris it should be as a randomizer

Optional steps to be able to launch through steam library/gamingmode:
Right Click tunic in lutris-create application menu shortcut-search for tunic in steam's system search- right click the tunic without an icon image-add to steam-Now that you have the Tunic randomizer as a non steam game-You can rename to something distinctive in properties and add in custom artwork by search "Tunic" in steamgriddb

Hope this might help somebody save the hours of trial and error I needed to go through to figure this out. Very new to linux so there are probably easier ways to get this to work, but this is what I could figure out.

**Comment by silent-destroyer** [comment]
Thanks for the info, glad you were able to get it working in the end. The current guide has worked for myself and several others, but good to have more options if it doesn't work for everyone.
