### ISSUE TITLE
GUI option for Fixed Shops displaying incorrectly

### ISSUE THREAD

**Issue by spaceglace** [silent-destroyer/tunic-randomizer#18]
### Expected Behaviour
The toggle for "fewer shops" in Single Player settings should reflect the TunicRandomizer.Settings.ERFixedShop setting and be toggleable from the options menu.

### Current Behaviour
The toggle for "fewer shops" correctly sets the behaviour, but does not display the state of that option.

### Possible Solution
Update the variable on line 64 of OptionsGUIPatches.cs from `TunicRandomizer.Settings.EntranceRandoEnabled` to `TunicRandomizer.Settings.ERFixedShop`.

### Steps to Reproduce
1. Open Single Player settings menu, toggle 'Fewer Shops' to be the opposite value of 'Entrance Randomizer'
2. Close menu and reopen
3. Observe state of Fewer Shops setting

### Detailed Information
Suspected issue is at: https://github.com/silent-destroyer/tunic-randomizer/blob/babc983c10f57d7a83d335debfd8bd2312e1021a/src/Patches/OptionsGUIPatches.cs#L64

**Comment by silent-destroyer** [comment]
Fixed in [commit e734851](https://github.com/silent-destroyer/tunic-randomizer/commit/e7348518844f68fab465cb25ebd6811350d1642e)
