### ISSUE TITLE
True Ending Not Working

### ISSUE THREAD

**Issue by SeraphinEveles** [silent-destroyer/tunic-randomizer#5]
With the current patch (0.0.16), the true ending doesn't happen if you collect all 28 pages before defeating The Heir.

**Comment by silent-destroyer** [comment]
The game is scripted to always start the boss fight the first time you interact with The Heir after placing the hexagons in the temple, even if you already have all 28 pages beforehand. Once the fight starts you can simply save and quit and then continue and you will spawn back in the arena and be able to activate the true ending. Or if you lose the fight you can just go back and get the true ending right away as well.

**Comment by SeraphinEveles** [comment]
I tried that, and it did not work, unless going back after getting the bad ending doesn't work.

**Comment by silent-destroyer** [comment]
Hmm, that definitely shouldn't be the case. Did you accidentally go into New Game+ after getting the bad ending? That would be the only thing I can think of that would cause it to not work, but I will try and see if I can reproduce this. If you still have the save file (%localappdata%low\Andrew Shouldice\Secret Legend\SAVES) could you attach it here?

**Comment by SeraphinEveles** [comment]
I'm *pretty* sure I did not. 
[001003885240-randomizer~001003895290.zip](https://github.com/silent-destroyer/tunic-randomizer/files/12388797/001003885240-randomizer.001003895290.zip)

**Comment by silent-destroyer** [comment]
I loaded that save file and went to the heir and was able to activate the true ending, and then also fought her, hit Retry and went back and was able to do the true ending as well. Are you still unable to do it on your end?

**Comment by SeraphinEveles** [comment]
The file seems to have completely broken for me. I'm going to run a new one and retest.

**Comment by SeraphinEveles** [comment]
Ok, now it's working. Might have just been something up with that save on my end, since it kinda wiped itself out. On a secondary note, there doesn't appear to be a way (at least not that's shown on-screen) to hide the items in the ending sequence.

**Comment by silent-destroyer** [comment]
Okay, glad that it's working now, if it ever comes up again don't hesitate to let me know again. As for hiding the items in the credits, I can try and make that happen as well.
