### ISSUE TITLE
Ghost hints not showing up on archipelago text client (or HintMachine)

### ISSUE THREAD

**Issue by POONpirate** [silent-destroyer/tunic-randomizer#83]
After updating from rando version 3.2.4 to 4.0.1 ghost fox hints are no longer showing up in archipelago text client or the third party tracking app HintMachine. When troubleshooting this i downgraded my server and forgot to downgrade the game and it still didn't send me hints on a freshly generated seed. When i did downgrade the game rando version it did start to give ghost fox hints again leading me to believe the issue is the game not sending the hints to the server.

**Comment by silent-destroyer** [comment]
Thanks for the report, I will look into it when I get a chance! In the meantime, I would double check that the setting for sending hints is enabled (in the options menu under Randomizer Settings -> Archipelago Settings -> Send hints to server). I don't think it would be the case, but it's possible it got turned off somehow after the update? I should also note that not every ghost hint can get sent as a hint, only certain ones do (ones that mention a specific location in your game e.g. mountain top, 20 fairies, etc.)
